### ISSUE TITLE
Should have - "Custom" template type

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas-cli#29]
## Expected Behaviour

It should be possible to "build" a function which isn't using one of the known / supported template types. An example would be the shrink_image example in the repo.

Snippet:

```yaml
  shrink-image:
    lang: custom
    handler: ./samples/image-magick
    image: functions/resizer
    fprocess: "convert - -resize 50% fd:1"
```

The context is whatever is in the `handler` folder and the Dockerfile in the root of the directory will be used for the build.

## Current Behaviour

Build manually and remove the `lang` element then mark the item as `skip_build`

## Possible Solution

When setting the language to `custom` then a `docker build` is invoked in the handler folder directly.

## Context

This will add versatility - especially for languages which don't suit dynamic templating like Golang.
