### ISSUE TITLE
Calling function created with `csharp` template results in error

### ISSUE THREAD

**Issue by ems5311** [alexellis/faas-cli#90]
When I try to call a function created with the C# template, I get the following result:

```
$ curl http://localhost:8080/function/csharp-hello-app -d "stuff"
exit status 145
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

This error code apparently indicates that the image that is built does not have the SDK installed. (https://stackoverflow.com/questions/42346498/dotnet-aspnetcore-docker-build-fails-with-a-145-error-code)

Are others seeing this issue? I'm deploying by adding the following to `./samples.yml`:
```
  functions:
    csharp-hello-app:
      lang: csharp
      handler: ./sample/csharp-hello
      image: yourname/csharp-hello-app
```

## Expected Behaviour

Csharp app echos input.

## Current Behaviour

Returns `exit status 145`

## Steps to Reproduce (for bugs)

1. Copy the following into the `functions:` block of your yaml file:
```
    csharp-hello-app:
      lang: csharp
      handler: ./sample/csharp-hello
      image: yourname/csharp-hello-app
```
2. run `faas-cli build -f <yourfile.yaml>`
3. run `faas-cli deploy -f <yourfile.yaml>`
4. `curl http://localhost:8080/function/csharp-hello-app -d "stuff"`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.1-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 16.04
* Link to your project or a code example to reproduce issue:
